import 'package:flutter/material.dart';

/* Text Order ID: 98787836
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrderID98787836Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.4000000059604645,
      child: Text(
        '''Order ID: 98787836''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.3999999364217122,
          fontSize: 12.0,
          fontFamily: 'Muli',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 30, 30, 30),

          /* letterSpacing: 0.0, */
        ),
      ),
    ));
  }
}
