import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedlogo1widget/generated/GeneratedGroupWidget8.dart';
import 'package:flutterapp/klickfreshapp/generatedlogo1widget/generated/GeneratedMachrangaWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/klickfreshapp/generatedlogo1widget/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/klickfreshapp/generatedlogo1widget/generated/GeneratedMachrangaWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedlogo1widget/generated/GeneratedMachrangaWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatedlogo1widget/generated/GeneratedGroupWidget6.dart';

/* Frame logo 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogo1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1366.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2158126272533858;

                  final double height =
                      constraints.maxHeight * 0.2820312976837158;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 1.3168375174437226,
                        y: constraints.maxHeight * -0.8026041984558105,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.36530014641288433;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 1.46915821170388,
                        y: constraints.maxHeight * -0.6796471277872721,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMachrangaWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3461200496288205;

                  final double height =
                      constraints.maxHeight * 0.45273439089457196;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3270863746654237,
                        y: constraints.maxHeight * 0.166015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.36530014641288433;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.31928484401451546,
                        y: constraints.maxHeight * 0.5547278722127279,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMachrangaWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.21581258257171942;

                  final double height =
                      constraints.maxHeight * 0.2820312976837158;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2326500642701089,
                        y: constraints.maxHeight * -0.8026041984558105,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.36530014641288433;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.38497080321193267,
                        y: constraints.maxHeight * -0.6796471277872721,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMachrangaWidget3(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
