import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedORDERHISTORYWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedGroup99Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedGroup100Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedGroup21Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget20.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedProcessingWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedGroup75Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedRectangle13Widget7.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget21.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_historywidget/generated/GeneratedGroup101Widget.dart';

/* Frame order_history
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrder_historyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget20(),
              ),
              Positioned(
                left: 16.0,
                top: 986.758056640625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.53216552734375,
                child: GeneratedGroup75Widget4(),
              ),
              Positioned(
                left: 113.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 148.0,
                height: 24.0,
                child: GeneratedORDERHISTORYWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 145.0,
                child: GeneratedGroup99Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 145.0,
                child: GeneratedGroup100Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 145.0,
                child: GeneratedGroup101Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 817.484375,
                right: null,
                bottom: null,
                width: 86.0,
                height: 27.0,
                child: GeneratedProcessingWidget3(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget21(),
              ),
              Positioned(
                left: 16.0,
                top: 859.85791015625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 58.0,
                child: GeneratedGroup21Widget4(),
              )
            ]),
      ),
    ));
  }
}
