import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/Generated560076Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedFrame10Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedDeliveringatWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget5.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedEllipse27Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedGroup104Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedNotification_iconWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget6.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedFeaturedProductsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedBannerWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedPOPULARProductsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget/generated/GeneratedGroup56Widget.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1241.22705078125,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1241.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 127.23260498046875,
                                    child: GeneratedRectangle13Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: null,
                                    width: null,
                                    height: 20.0,
                                    child:
                                        GeneratedStatusbarsiPhone8statusbarlightWidget5(),
                                  ),
                                  Positioned(
                                    left: 335.0,
                                    top: 44.34490966796875,
                                    right: null,
                                    bottom: null,
                                    width: 24.0,
                                    height: 24.0,
                                    child: GeneratedNotification_iconWidget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 488.5722961425781,
                                    right: null,
                                    bottom: null,
                                    width: 201.0,
                                    height: 24.0,
                                    child: GeneratedFeaturedProductsWidget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 835.8880004882812,
                                    right: null,
                                    bottom: null,
                                    width: 193.0,
                                    height: 24.0,
                                    child: GeneratedPOPULARProductsWidget(),
                                  ),
                                  Positioned(
                                    left: 13.537353515625,
                                    top: 91.52459716796875,
                                    right: null,
                                    bottom: null,
                                    width: 347.92535400390625,
                                    height: 46.0,
                                    child: GeneratedGroup104Widget(),
                                  ),
                                  Positioned(
                                    left: 167.0,
                                    top: 54.0,
                                    right: null,
                                    bottom: null,
                                    width: 63.0,
                                    height: 24.0,
                                    child: Generated560076Widget(),
                                  ),
                                  Positioned(
                                    left: 154.0,
                                    top: 37.0,
                                    right: null,
                                    bottom: null,
                                    width: 73.0,
                                    height: 19.0,
                                    child: GeneratedDeliveringatWidget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 158.45953369140625,
                                    right: null,
                                    bottom: null,
                                    width: 350.0,
                                    height: 180.0,
                                    child: GeneratedBannerWidget(),
                                  ),
                                  Positioned(
                                    left: 18.0,
                                    top: 374.0,
                                    right: null,
                                    bottom: null,
                                    width: 342.0,
                                    height: 84.0,
                                    child: GeneratedFrame7Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 528.0,
                                    right: null,
                                    bottom: null,
                                    width: 342.0,
                                    height: 273.0,
                                    child: GeneratedFrame9Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 875.315673828125,
                                    right: null,
                                    bottom: null,
                                    width: 342.0,
                                    height: 273.0,
                                    child: GeneratedFrame10Widget(),
                                  ),
                                  Positioned(
                                    left: 14.0,
                                    top: 40.28277587890625,
                                    right: null,
                                    bottom: null,
                                    width: 135.25238037109375,
                                    height: 45.22206115722656,
                                    child: GeneratedGroup56Widget(),
                                  ),
                                  Positioned(
                                    left: -0.5,
                                    top: 0.0,
                                    right: 0.5,
                                    bottom: null,
                                    width: null,
                                    height: 20.0,
                                    child:
                                        GeneratedStatusbarsiPhone8statusbarlightWidget6(),
                                  ),
                                  Positioned(
                                    left: 151.0,
                                    top: 1189.0,
                                    right: null,
                                    bottom: null,
                                    width: 11.0,
                                    height: 11.0,
                                    child: GeneratedEllipse27Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: -0.22705078125,
              width: 375.0,
              height: 58.0,
              child: GeneratedGroup21Widget(),
            )
          ]),
    ));
  }
}
