import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedDeliveryFeesWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedChickenThingSkinlessWidget35.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedQty1Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedDeliveringhereWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedQty1Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedBillingdetailsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedGroup78Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/Generated150Widget33.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget36.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedPrice3itemsWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedGroup95Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedGroup53Widget31.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget23.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget22.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/Generated35Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedORDERDETAILSWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedRectangle41Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedChickenThingSkinlessWidget36.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedBack_blackWidget13.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedORderstatusWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget37.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedTotal485Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedRectangle13Widget15.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedOrderID98787836Widget9.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/Generated150Widget32.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/GeneratedLine2Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_detailswidget/generated/Generated450Widget1.dart';

/* Frame order_details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrder_detailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 890.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget36(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget37(),
              ),
              Positioned(
                left: 16.0,
                top: 418.3443908691406,
                right: null,
                bottom: null,
                width: 164.0,
                height: 24.0,
                child: GeneratedDeliveringhereWidget1(),
              ),
              Positioned(
                left: 152.5,
                top: 137.50369262695312,
                right: null,
                bottom: null,
                width: 193.2138671875,
                height: 20.0,
                child: GeneratedChickenThingSkinlessWidget35(),
              ),
              Positioned(
                left: 152.5,
                top: 267.3097229003906,
                right: null,
                bottom: null,
                width: 193.2138671875,
                height: 20.0,
                child: GeneratedChickenThingSkinlessWidget36(),
              ),
              Positioned(
                left: 325.63623046875,
                top: 197.82241821289062,
                right: null,
                bottom: null,
                width: 38.0,
                height: 23.0,
                child: Generated150Widget32(),
              ),
              Positioned(
                left: 325.63623046875,
                top: 327.6284484863281,
                right: null,
                bottom: null,
                width: 38.0,
                height: 23.0,
                child: Generated150Widget33(),
              ),
              Positioned(
                left: 16.0,
                top: 137.50369262695312,
                right: null,
                bottom: null,
                width: 120.6573715209961,
                height: 86.68103790283203,
                child: GeneratedGroup53Widget31(),
              ),
              Positioned(
                left: 16.0,
                top: 267.3097229003906,
                right: null,
                bottom: null,
                width: 120.6573715209961,
                height: 86.68103790283203,
                child: GeneratedGroup78Widget5(),
              ),
              Positioned(
                left: 152.5,
                top: 157.09439086914062,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 36.0,
                child: GeneratedGrossWt900gmsNetWt500gmsWidget22(),
              ),
              Positioned(
                left: 152.5,
                top: 198.82241821289062,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 19.0,
                child: GeneratedQty1Widget2(),
              ),
              Positioned(
                left: 152.5,
                top: 328.6284484863281,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 19.0,
                child: GeneratedQty1Widget3(),
              ),
              Positioned(
                left: 152.5,
                top: 286.9004211425781,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 36.0,
                child: GeneratedGrossWt900gmsNetWt500gmsWidget23(),
              ),
              Positioned(
                left: 16.0,
                top: 375.3647766113281,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine2Widget5(),
              ),
              Positioned(
                left: 15.63623046875,
                top: 451.3144836425781,
                right: null,
                bottom: null,
                width: 343.0,
                height: 80.41822052001953,
                child: GeneratedRectangle41Widget3(),
              ),
              Positioned(
                left: 29.5283203125,
                top: 469.1854553222656,
                right: null,
                bottom: null,
                width: 316.60791015625,
                height: 46.0,
                child:
                    Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget5(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget13(),
              ),
              Positioned(
                left: 115.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 144.0,
                height: 24.0,
                child: GeneratedORDERDETAILSWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 105.03387451171875,
                right: null,
                bottom: null,
                width: 113.0,
                height: 19.0,
                child: GeneratedOrderID98787836Widget9(),
              ),
              Positioned(
                left: 16.63623046875,
                top: 571.2330932617188,
                right: null,
                bottom: null,
                width: 138.0,
                height: 24.0,
                child: GeneratedORderstatusWidget1(),
              ),
              Positioned(
                left: 15.63623046875,
                top: 706.483154296875,
                right: null,
                bottom: null,
                width: 152.0,
                height: 24.0,
                child: GeneratedBillingdetailsWidget(),
              ),
              Positioned(
                left: 16.63623046875,
                top: 616.6791381835938,
                right: null,
                bottom: null,
                width: 341.16375732421875,
                height: 51.06610870361328,
                child: GeneratedGroup95Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 817.7813720703125,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine5Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 817.7813720703125,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine4Widget1(),
              ),
              Positioned(
                left: 15.43603515625,
                top: 749.234130859375,
                right: null,
                bottom: null,
                width: 107.0,
                height: 24.0,
                child: GeneratedPrice3itemsWidget1(),
              ),
              Positioned(
                left: 15.43603515625,
                top: 780.8251953125,
                right: null,
                bottom: null,
                width: 105.0,
                height: 24.0,
                child: GeneratedDeliveryFeesWidget1(),
              ),
              Positioned(
                left: 320.0,
                top: 751.234130859375,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: Generated450Widget1(),
              ),
              Positioned(
                left: 330.0,
                top: 782.8251953125,
                right: null,
                bottom: null,
                width: 34.0,
                height: 27.0,
                child: Generated35Widget1(),
              ),
              Positioned(
                left: 278.755859375,
                top: 825.50927734375,
                right: null,
                bottom: null,
                width: 82.0,
                height: 20.0,
                child: GeneratedTotal485Widget1(),
              )
            ]),
      ),
    ));
  }
}
