import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedBack_blackWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedGroup52Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedMobileNoWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedStatusbarsiPhone8statusbarlightWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedAgreetoalltermsandconditionsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget2/generated/GeneratedAlreadyhaveanaccountLoginWidget.dart';

/* Frame welcome
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget3(),
              ),
              Positioned(
                left: 103.6632080078125,
                top: 570.203857421875,
                right: null,
                bottom: null,
                width: 179.0,
                height: 50.0,
                child: GeneratedAlreadyhaveanaccountLoginWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 26.0,
                child: GeneratedAgreetoalltermsandconditionsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 503.6014099121094,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget2(),
              ),
              Positioned(
                left: 19.5,
                top: 47.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget1(),
              ),
              Positioned(
                left: 149.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 76.0,
                height: 24.0,
                child: GeneratedSIGNUPWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 28.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 273.0169982910156,
                right: null,
                bottom: null,
                width: 76.0,
                height: 25.0,
                child: GeneratedMobileNoWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 28.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 28.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 644.017333984375,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 564.0,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 483.9830017089844,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 404.0,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRectangle28Widget(),
              )
            ]),
      ),
    ));
  }
}
