import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup84widget4/generated/GeneratedMaskGroupWidget45.dart';

/* Group Group 84
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup84Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 83.13725280761719,
      height: 59.72633743286133,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 83.13725280761719,
              height: 59.72633743286133,
              child: GeneratedMaskGroupWidget45(),
            )
          ]),
    ));
  }
}
