import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedGroupWidget20.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedMaskGroupWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedWedeliverfreshmeatatyourdoorstepwithin90minutesToorderl.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedMaskGroupWidget4.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedImage13Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget/generated/GeneratedWelcometoMachrangaWidget.dart';

/* Frame welcome
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget1(),
              ),
              Positioned(
                left: 15.99993896484375,
                top: 666.0525512695312,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget(),
              ),
              Positioned(
                left: 15.99993896484375,
                top: 732.3665771484375,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup53Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 163.02618408203125,
                right: null,
                bottom: null,
                width: 300.0,
                height: 34.0,
                child: GeneratedWelcometoMachrangaWidget(),
              ),
              Positioned(
                left: 33.49993896484375,
                top: 196.3402862548828,
                right: null,
                bottom: null,
                width: 308.00006103515625,
                height: 81.75397491455078,
                child:
                    GeneratedWedeliverfreshmeatatyourdoorstepwithin90minutesToorderl(),
              ),
              Positioned(
                left: 58.83253479003906,
                top: 353.6210632324219,
                right: null,
                bottom: null,
                width: 257.3349609375,
                height: 258.3756408691406,
                child: GeneratedMaskGroupWidget3(),
              ),
              Positioned(
                left: 54.05975341796875,
                top: 329.1100158691406,
                right: null,
                bottom: null,
                width: 266.8805236816406,
                height: 267.3977355957031,
                child: GeneratedImage13Widget(),
              ),
              Positioned(
                left: 57.18304443359375,
                top: 349.1100158691406,
                right: null,
                bottom: null,
                width: 257.3349609375,
                height: 258.3756408691406,
                child: GeneratedMaskGroupWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3163289998372396;

                  final double height =
                      constraints.maxHeight * 0.10830103117844155;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.34183544921875,
                        y: constraints.maxHeight * 0.08379044556265394,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget20(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
