import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup92widget/generated/GeneratedGroup87Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup92widget/generated/GeneratedGroup89Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup92widget/generated/GeneratedGroup91Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup92widget/generated/GeneratedGroup88Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup92widget/generated/GeneratedGroup90Widget.dart';

/* Group Group 92
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup92Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 605.0218505859375,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 88.6810302734375,
              child: GeneratedGroup87Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 129.4285888671875,
              right: null,
              bottom: null,
              width: 343.0,
              height: 88.6810302734375,
              child: GeneratedGroup88Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 257.483642578125,
              right: null,
              bottom: null,
              width: 343.0,
              height: 88.6810302734375,
              child: GeneratedGroup89Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 386.9122009277344,
              right: null,
              bottom: null,
              width: 343.0,
              height: 88.68106079101562,
              child: GeneratedGroup90Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 516.3407592773438,
              right: null,
              bottom: null,
              width: 343.0,
              height: 88.68109130859375,
              child: GeneratedGroup91Widget(),
            )
          ]),
    ));
  }
}
