import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedWehavesentananOTPtoyourmobilenoWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedGroup52Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedStatusbarsiPhone8statusbarlightWidget4.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedBack_blackWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedENTEROTPWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget3/generated/GeneratedEnterOTPWidget.dart';

/* Frame welcome
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomeWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget4(),
              ),
              Positioned(
                left: 15.0,
                top: 110.00387573242188,
                right: null,
                bottom: null,
                width: 79.0,
                height: 25.0,
                child: GeneratedEnterOTPWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 644.017333984375,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 15.0,
                top: 175.50787353515625,
                right: null,
                bottom: null,
                width: 299.0,
                height: 26.0,
                child: GeneratedWehavesentananOTPtoyourmobilenoWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 226.50787353515625,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget3(),
              ),
              Positioned(
                left: 19.5,
                top: 47.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget2(),
              ),
              Positioned(
                left: 136.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 103.0,
                height: 24.0,
                child: GeneratedENTEROTPWidget(),
              )
            ]),
      ),
    ));
  }
}
