import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedSorryyouhaventaddedanyproductintoyourcartWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget27.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedGroup21Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget26.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedCARTWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedSubtractWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedRectangle13Widget10.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget1/generated/GeneratedEMPTYCARTWidget.dart';

/* Frame pay
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPayWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 127.23260498046875,
                      child: GeneratedRectangle13Widget10(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget26(),
                    ),
                    Positioned(
                      left: 162.5,
                      top: 45.5,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 27.0,
                      child: GeneratedCARTWidget1(),
                    ),
                    Positioned(
                      left: 129.0,
                      top: 398.0,
                      right: null,
                      bottom: null,
                      width: 119.0,
                      height: 24.0,
                      child: GeneratedEMPTYCARTWidget(),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 420.0,
                      right: null,
                      bottom: null,
                      width: 270.0,
                      height: 46.0,
                      child:
                          GeneratedSorryyouhaventaddedanyproductintoyourcartWidget(),
                    ),
                    Positioned(
                      left: -0.5,
                      top: 0.0,
                      right: 0.5,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget27(),
                    ),
                    Positioned(
                      left: 111.0,
                      top: 279.0,
                      right: null,
                      bottom: null,
                      width: 151.99998474121094,
                      height: 99.0,
                      child: GeneratedSubtractWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 58.0,
              child: GeneratedGroup21Widget5(),
            )
          ]),
    ));
  }
}
