import 'package:flutter/material.dart';

/* Rectangle image 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1050.0,
      height: 1067.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2327546a1d67378c380c1876fe62311e8135ac1e.png",
          color: null,
          fit: BoxFit.cover,
          width: 1050.0,
          height: 1067.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
