import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedFISRTTIME10Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAPPLYWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedEllipse25Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedGet10discountonyourfirstorderWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedUsercodeFIRSTTIME10andget10discountonyourfirstappWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedFISRTTIME10Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedGet10discountonyourfirstorderWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAPPLYWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedRectangle13Widget18.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedBack_blackWidget15.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAPPLYWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedUsercodeFIRSTTIME10andget10discountonyourfirstappWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget41.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquaWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedTermsandconditionsWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedShowmoreWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedShowmoreWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAPPLYWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquaWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedFISRTTIME10Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedEnterpromocodehereWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedEllipse24Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedUsercodeFIRSTTIME10andget10discountonyourfirstappWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedEllipse26Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedGet10discountonyourfirstorderWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedLine2Widget6.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget1/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquaWidget1.dart';

/* Frame edit_profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEdit_profileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 86.78026580810547,
                right: null,
                bottom: null,
                width: 374.93988037109375,
                height: 741.4043579101562,
                child: GeneratedRectangle13Widget18(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget15(),
              ),
              Positioned(
                left: 52.194435119628906,
                top: 45.5,
                right: null,
                bottom: null,
                width: 169.0,
                height: 24.0,
                child: GeneratedEnterpromocodehereWidget(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget41(),
              ),
              Positioned(
                left: 16.0,
                top: 110.823974609375,
                right: null,
                bottom: null,
                width: 129.65481567382812,
                height: 34.64448928833008,
                child: GeneratedRectangle51Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 443.1235046386719,
                right: null,
                bottom: null,
                width: 129.65481567382812,
                height: 34.64448928833008,
                child: GeneratedRectangle52Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 616.1151733398438,
                right: null,
                bottom: null,
                width: 129.65481567382812,
                height: 34.64448928833008,
                child: GeneratedRectangle53Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 119.64620971679688,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedFISRTTIME10Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 451.94573974609375,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedFISRTTIME10Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 624.9374389648438,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedFISRTTIME10Widget2(),
              ),
              Positioned(
                left: 305.7001953125,
                top: 118.64620971679688,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: GeneratedAPPLYWidget(),
              ),
              Positioned(
                left: 305.7001953125,
                top: 47.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: GeneratedAPPLYWidget1(),
              ),
              Positioned(
                left: 305.7001953125,
                top: 450.94573974609375,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: GeneratedAPPLYWidget2(),
              ),
              Positioned(
                left: 305.7001953125,
                top: 623.9374389648438,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: GeneratedAPPLYWidget3(),
              ),
              Positioned(
                left: 19.0,
                top: 158.55950927734375,
                right: null,
                bottom: null,
                width: 282.0,
                height: 21.0,
                child: GeneratedGet10discountonyourfirstorderWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 490.8590393066406,
                right: null,
                bottom: null,
                width: 282.0,
                height: 21.0,
                child: GeneratedGet10discountonyourfirstorderWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 663.8507080078125,
                right: null,
                bottom: null,
                width: 282.0,
                height: 21.0,
                child: GeneratedGet10discountonyourfirstorderWidget2(),
              ),
              Positioned(
                left: 19.0,
                top: 179.55950927734375,
                right: null,
                bottom: null,
                width: 326.0,
                height: 42.0,
                child:
                    GeneratedUsercodeFIRSTTIME10andget10discountonyourfirstappWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 511.8590393066406,
                right: null,
                bottom: null,
                width: 326.0,
                height: 42.0,
                child:
                    GeneratedUsercodeFIRSTTIME10andget10discountonyourfirstappWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 684.8507080078125,
                right: null,
                bottom: null,
                width: 326.0,
                height: 42.0,
                child:
                    GeneratedUsercodeFIRSTTIME10andget10discountonyourfirstappWidget2(),
              ),
              Positioned(
                left: 19.0,
                top: 228.70550537109375,
                right: null,
                bottom: null,
                width: 140.0,
                height: 22.0,
                child: GeneratedTermsandconditionsWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 562.0050048828125,
                right: null,
                bottom: null,
                width: 76.0,
                height: 22.0,
                child: GeneratedShowmoreWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 734.9966430664062,
                right: null,
                bottom: null,
                width: 76.0,
                height: 22.0,
                child: GeneratedShowmoreWidget1(),
              ),
              Positioned(
                left: 35.99951171875,
                top: 257.85150146484375,
                right: null,
                bottom: null,
                width: 321.5,
                height: 42.0,
                child:
                    GeneratedAmetminimmollitnondeseruntullamcoestsitaliquaWidget(),
              ),
              Positioned(
                left: 35.99951171875,
                top: 316.1195068359375,
                right: null,
                bottom: null,
                width: 321.5,
                height: 42.0,
                child:
                    GeneratedAmetminimmollitnondeseruntullamcoestsitaliquaWidget1(),
              ),
              Positioned(
                left: 35.99951171875,
                top: 366.9735107421875,
                right: null,
                bottom: null,
                width: 321.5,
                height: 42.0,
                child:
                    GeneratedAmetminimmollitnondeseruntullamcoestsitaliquaWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 88.6619873046875,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 427.69134521484375,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine2Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 600.6830444335938,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 264.5631103515625,
                right: null,
                bottom: null,
                width: 11.586402893066406,
                height: 11.586402893066406,
                child: GeneratedEllipse24Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 322.83111572265625,
                right: null,
                bottom: null,
                width: 11.586402893066406,
                height: 11.586402893066406,
                child: GeneratedEllipse25Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 373.68511962890625,
                right: null,
                bottom: null,
                width: 11.586402893066406,
                height: 11.586402893066406,
                child: GeneratedEllipse26Widget1(),
              )
            ]),
      ),
    ));
  }
}
