import 'package:flutter/material.dart';

/* Rectangle image 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 61.753997802734375,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/0b67c4574123c5baf99acfbb3f6db45183dce477.png",
          color: null,
          fit: BoxFit.cover,
          width: 375.0,
          height: 61.753997802734375,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
