import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedStatusbarsiPhone8statusbarlightWidget9.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedGroup81Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedGroup84Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedEnterPincodeWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedGroup52Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedCheckDeliveryAvailabilityWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedStatusbarsiPhone8statusbarlightWidget11.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedDetectmylocationWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedhomewidget4/generated/GeneratedRectangle15Widget3.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 247, 247),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget9(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.5,
                height: 896.2269897460938,
                child: GeneratedGroup81Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.79827880859375,
                height: 896.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.79827880859375,
                height: 230.8174285888672,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 247.34375,
                top: 108.90814971923828,
                right: null,
                bottom: null,
                width: 114.0,
                height: 20.0,
                child: GeneratedDetectmylocationWidget(),
              ),
              Positioned(
                left: 224.44808959960938,
                top: 108.36117553710938,
                right: null,
                bottom: null,
                width: 19.09395408630371,
                height: 19.09395408630371,
                child: GeneratedGroup84Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 154.89793395996094,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget4(),
              ),
              Positioned(
                left: 15.36376953125,
                top: 70.91943359375,
                right: null,
                bottom: null,
                width: 213.0,
                height: 21.0,
                child: GeneratedCheckDeliveryAvailabilityWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 106.02459716796875,
                right: null,
                bottom: null,
                width: 104.0,
                height: 24.0,
                child: GeneratedEnterPincodeWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 759.5440673828125,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle15Widget3(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget11(),
              )
            ]),
      ),
    ));
  }
}
