import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup53widget45/generated/GeneratedMaskGroupWidget79.dart';

/* Group Group 53
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup53Widget45 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 500.0,
      height: 500.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 500.0,
              height: 500.0,
              child: GeneratedMaskGroupWidget79(),
            )
          ]),
    ));
  }
}
