import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup89widget1/generated/GeneratedGroup87Widget1.dart';

/* Group Group 89
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup89Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1439.0,
      height: 503.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1439.0,
              height: 503.0,
              child: GeneratedGroup87Widget1(),
            )
          ]),
    ));
  }
}
