import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup91widget2/generated/GeneratedGroup53Widget43.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup91widget2/generated/Generated150Widget45.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup91widget2/generated/GeneratedGrossWt900gmsNetWt500gmsWidget34.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup91widget2/generated/GeneratedRectangleWidget190.dart';
import 'package:flutterapp/klickfreshapp/generatedgroup91widget2/generated/GeneratedChickenThingSkinlessWidget48.dart';

/* Group Group 91
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup91Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 273.23681640625,
      height: 326.478515625,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.5997618436813354,
              right: null,
              bottom: null,
              width: 273.23681640625,
              height: 325.8787536621094,
              child: GeneratedRectangleWidget190(),
            ),
            Positioned(
              left: 13.344586372375488,
              top: 220.29144287109375,
              right: null,
              bottom: null,
              width: 241.3955535888672,
              height: 25.81421661376953,
              child: GeneratedChickenThingSkinlessWidget48(),
            ),
            Positioned(
              left: 212.6319580078125,
              top: 280.27459716796875,
              right: null,
              bottom: null,
              width: 46.361534118652344,
              height: 27.560836791992188,
              child: Generated150Widget45(),
            ),
            Positioned(
              left: 13.344589233398438,
              top: 243.36724853515625,
              right: null,
              bottom: null,
              width: 255.18272399902344,
              height: 44.61491394042969,
              child: GeneratedGrossWt900gmsNetWt500gmsWidget34(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 273.1329040527344,
              height: 199.0762481689453,
              child: GeneratedGroup53Widget43(),
            )
          ]),
    ));
  }
}
