import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedEllipse18Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle13Widget8.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedDetectmylocationWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget22.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedStateWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedBack_blackWidget8.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedGroup75Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget23.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedAddressline1Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedGroup52Widget8.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedADDADDRESSWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle45Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedSetasdefaultaddressWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle44Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedEllipse19Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedAddressline2Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedRectangle15Widget8.dart';
import 'package:flutterapp/klickfreshapp/generatedadd_addresswidget/generated/GeneratedZipCodeWidget.dart';

/* Frame add_address
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdd_addressWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget22(),
              ),
              Positioned(
                left: 16.0,
                top: 986.758056640625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.53216552734375,
                child: GeneratedGroup75Widget5(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget8(),
              ),
              Positioned(
                left: 122.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 131.0,
                height: 24.0,
                child: GeneratedADDADDRESSWidget(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget23(),
              ),
              Positioned(
                left: 50.0,
                top: 355.0169982910156,
                right: null,
                bottom: null,
                width: 154.0,
                height: 26.0,
                child: GeneratedSetasdefaultaddressWidget(),
              ),
              Positioned(
                left: 227.34381103515625,
                top: 107.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 26.0,
                child: GeneratedDetectmylocationWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 408.5,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget8(),
              ),
              Positioned(
                left: 16.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 25.0,
                child: GeneratedAddressline2Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 273.0169982910156,
                right: null,
                bottom: null,
                width: 66.0,
                height: 25.0,
                child: GeneratedZipCodeWidget(),
              ),
              Positioned(
                left: 195.34375,
                top: 273.0169982910156,
                right: null,
                bottom: null,
                width: 42.0,
                height: 28.0,
                child: GeneratedStateWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 25.0,
                child: GeneratedAddressline1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 644.017333984375,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle15Widget8(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 564.0,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle16Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 483.9830017089844,
                width: 164.0,
                height: 1.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 195.34375,
                top: null,
                right: null,
                bottom: 483.9830017089844,
                width: 164.0,
                height: 1.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 355.0169982910156,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRectangle28Widget2(),
              ),
              Positioned(
                left: 206.11936950683594,
                top: 109.5694808959961,
                right: null,
                bottom: null,
                width: 18.86104393005371,
                height: 18.86104393005371,
                child: GeneratedEllipse18Widget1(),
              ),
              Positioned(
                left: 214.6625213623047,
                top: 109.33658599853516,
                right: null,
                bottom: null,
                width: 2.2636680603027344,
                height: 19.09395408630371,
                child: GeneratedRectangle44Widget1(),
              ),
              Positioned(
                left: 225.0966339111328,
                top: 117.751708984375,
                right: null,
                bottom: null,
                width: 2.2636680603027344,
                height: 19.09395408630371,
                child: GeneratedRectangle45Widget1(),
              ),
              Positioned(
                left: 209.1920623779297,
                top: 112.64253997802734,
                right: null,
                bottom: null,
                width: 12.714980125427246,
                height: 12.714980125427246,
                child: GeneratedEllipse19Widget1(),
              )
            ]),
      ),
    ));
  }
}
