import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedfigma_thumbnailwidget/generated/GeneratedLogoWidget2.dart';

/* Frame figma_thumbnail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFigma_thumbnailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 519.0,
        height: 278.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 133.0,
                top: 23.345651626586914,
                right: null,
                bottom: null,
                width: 252.0,
                height: 237.47862243652344,
                child: GeneratedLogoWidget2(),
              )
            ]),
      ),
    ));
  }
}
