import 'package:flutter/material.dart';

/* Text Fish ---Sweet water fish ---Sea fish chicken mutton premium meat frozon Sausages - salami marinated ---Fish ---Chicken Hot Deal Recipe
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFishSweetwaterfishSeafishchickenmuttonpremiummeatfrozon
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Fish
 ---Sweet water fish
 ---Sea fish
chicken
mutton
premium meat
frozon
Sausages - salami
marinated
 ---Fish
 ---Chicken
Hot Deal
Recipe
''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3350000381469727,
        fontSize: 12.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
