import 'package:flutter/material.dart';

/* Text Chicken Thing - Skinless + others
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChickenThingSkinlessothersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Chicken Thing - Skinless + others''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.218000054359436,
        fontSize: 16.0,
        fontFamily: 'GalanoGrotesque-SemiBold',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 30, 30, 30),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
