import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedGroup75Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedFrame7Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedCHICKENWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedBack_blackWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget12.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget13.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedGroup78Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedGroup77Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget/generated/GeneratedRectangle13Widget3.dart';

/* Frame catergory
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCatergoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 247, 247),
                ),
              ),
              Positioned(
                left: -6.950927734375,
                top: -17.523193359375,
                right: null,
                bottom: null,
                width: 389.1697692871094,
                height: 193.66864013671875,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 86.098388671875,
                right: null,
                bottom: null,
                width: 342.0,
                height: 84.0,
                child: GeneratedFrame7Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget12(),
              ),
              Positioned(
                left: 16.0,
                top: 188.69638061523438,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.3105773925781,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 475.9201354980469,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.3105773925781,
                child: GeneratedGroup77Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 763.1436767578125,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.3105773925781,
                child: GeneratedGroup78Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 986.758056640625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.53216552734375,
                child: GeneratedGroup75Widget(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget3(),
              ),
              Positioned(
                left: 145.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 88.0,
                height: 27.0,
                child: GeneratedCHICKENWidget(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget13(),
              )
            ]),
      ),
    ));
  }
}
