import 'package:flutter/material.dart';

/* Text machranga
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMachrangaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''machranga''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1718750252376866,
        fontSize: 94.46926879882812,
        fontFamily: 'Nanotech LLC',
        fontWeight: FontWeight.w400,

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
