import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedRozarpayWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedGroup76Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedRectangle13Widget9.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedPAYMENTWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedADDRESSANDPAYMENTWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget24.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget25.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedRectangle27Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedDeliverhereWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedCashOnDeliveryWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedGroup75Widget6.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedBack_blackWidget9.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedGroup52Widget9.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedpaywidget/generated/GeneratedEllipse17Widget.dart';

/* Frame pay
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPayWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget24(),
              ),
              Positioned(
                left: 16.0,
                top: 986.758056640625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.53216552734375,
                child: GeneratedGroup75Widget6(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget9(),
              ),
              Positioned(
                left: 76.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 222.0,
                height: 24.0,
                child: GeneratedADDRESSANDPAYMENTWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 329.9688720703125,
                right: null,
                bottom: null,
                width: 92.0,
                height: 27.0,
                child: GeneratedPAYMENTWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 103.47109985351562,
                right: null,
                bottom: null,
                width: 132.0,
                height: 24.0,
                child: GeneratedDeliverhereWidget(),
              ),
              Positioned(
                left: -3.84912109375,
                top: 738.6762084960938,
                right: null,
                bottom: null,
                width: 382.6983947753906,
                height: 74.32378387451172,
                child: GeneratedRectangle27Widget2(),
              ),
              Positioned(
                left: 15.755859375,
                top: 749.6027221679688,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget9(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget25(),
              ),
              Positioned(
                left: 16.0,
                top: 366.07598876953125,
                right: null,
                bottom: null,
                width: 343.0,
                height: 53.47540283203125,
                child: GeneratedRectangle42Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 433.658447265625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 53.47540283203125,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 67.7255859375,
                top: 382.313720703125,
                right: null,
                bottom: null,
                width: 130.0,
                height: 24.0,
                child: GeneratedCashOnDeliveryWidget(),
              ),
              Positioned(
                left: 67.7255859375,
                top: 449.8961181640625,
                right: null,
                bottom: null,
                width: 77.0,
                height: 27.0,
                child: GeneratedRozarpayWidget(),
              ),
              Positioned(
                left: 31.39208984375,
                top: 382.38494873046875,
                right: null,
                bottom: null,
                width: 20.85758399963379,
                height: 20.85758399963379,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 31.39208984375,
                top: 449.96734619140625,
                right: null,
                bottom: null,
                width: 20.85758399963379,
                height: 20.85758399963379,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 35.32080078125,
                top: 386.31378173828125,
                right: null,
                bottom: null,
                width: 12.999980926513672,
                height: 12.999980926513672,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 139.51654052734375,
                right: null,
                bottom: null,
                width: 343.0,
                height: 144.92457580566406,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 29.89208984375,
                top: 160.38755798339844,
                right: null,
                bottom: null,
                width: 316.60791015625,
                height: 46.0,
                child:
                    Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 546.0450134277344,
                width: 314.48822021484375,
                height: 40.70848083496094,
                child: TransformHelper.translate(
                    x: -0.24, y: 0.00, z: 0, child: GeneratedGroup76Widget4()),
              )
            ]),
      ),
    ));
  }
}
