import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget32.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget33.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedEditWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedEllipse18Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedBack_blackWidget11.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedGroup83Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedGroup52Widget10.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedEllipse19Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedRectangle27Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedEllipse17Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedRectangle13Widget13.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedGroup75Widget7.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedEllipse14Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedmanage_addresswidget/generated/GeneratedADDRESSWidget.dart';

/* Frame manage_address
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManage_addressWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget13(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget32(),
              ),
              Positioned(
                left: 16.0,
                top: 986.758056640625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.53216552734375,
                child: GeneratedGroup75Widget7(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget11(),
              ),
              Positioned(
                left: 143.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 91.0,
                height: 27.0,
                child: GeneratedADDRESSWidget(),
              ),
              Positioned(
                left: -3.84912109375,
                top: 738.6762084960938,
                right: null,
                bottom: null,
                width: 382.6983947753906,
                height: 74.32378387451172,
                child: GeneratedRectangle27Widget3(),
              ),
              Positioned(
                left: 15.755859375,
                top: 749.6027221679688,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget10(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget33(),
              ),
              Positioned(
                left: 16.0,
                top: 168.19131469726562,
                right: null,
                bottom: null,
                width: 343.0,
                height: 85.74202728271484,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: 31.39208984375,
                top: 194.19003295898438,
                right: null,
                bottom: null,
                width: 20.85758399963379,
                height: 20.85758399963379,
                child: GeneratedEllipse17Widget1(),
              ),
              Positioned(
                left: 35.32080078125,
                top: 198.11886596679688,
                right: null,
                bottom: null,
                width: 12.999980926513672,
                height: 12.999980926513672,
                child: GeneratedEllipse18Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 273.51287841796875,
                right: null,
                bottom: null,
                width: 343.0,
                height: 83.13055419921875,
                child: GeneratedRectangle42Widget1(),
              ),
              Positioned(
                left: 31.39208984375,
                top: 293.83917236328125,
                right: null,
                bottom: null,
                width: 20.85758399963379,
                height: 20.85758399963379,
                child: GeneratedEllipse14Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 376.70953369140625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 83.13055419921875,
                child: GeneratedRectangle43Widget1(),
              ),
              Positioned(
                left: 64.04765319824219,
                top: 193.42901611328125,
                right: null,
                bottom: null,
                width: 282.45233154296875,
                height: 46.0,
                child:
                    Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget1(),
              ),
              Positioned(
                left: 64.04765319824219,
                top: 291.75054931640625,
                right: null,
                bottom: null,
                width: 282.45233154296875,
                height: 46.0,
                child:
                    Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget2(),
              ),
              Positioned(
                left: 64.04765319824219,
                top: 394.94720458984375,
                right: null,
                bottom: null,
                width: 282.45233154296875,
                height: 46.0,
                child:
                    Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 99.52459716796875,
                right: null,
                bottom: null,
                width: 343.0,
                height: 53.47540283203125,
                child: GeneratedGroup83Widget1(),
              ),
              Positioned(
                left: 322.5,
                top: 176.42901611328125,
                right: null,
                bottom: null,
                width: 27.0,
                height: 22.0,
                child: GeneratedEditWidget(),
              ),
              Positioned(
                left: 31.39208984375,
                top: 397.417236328125,
                right: null,
                bottom: null,
                width: 20.85758399963379,
                height: 20.85758399963379,
                child: GeneratedEllipse19Widget2(),
              )
            ]),
      ),
    ));
  }
}
