import 'package:flutter/material.dart';

/* Text Home Products About us Contact
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeProductsAboutusContactWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Home        Products        About us         Contact ''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 1.171875,
        fontSize: 18.0,
        fontFamily: 'Biotif',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 30, 30, 30),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
