import 'package:flutter/material.dart';

/* Text MY ORDERS PRODUCT DETAILS
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMYORDERSPRODUCTDETAILSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''MY ORDERS
PRODUCT DETAILS

''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.218000094095866,
        fontSize: 12.0,
        fontFamily: 'GalanoGrotesque-SemiBold',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
