import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedDeliveryFeesWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedChickenThingSkinlessWidget21.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedChickenThingSkinlessWidget22.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedHaveapromocodeWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedPrice3itemsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle29Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/Generated150Widget21.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup76Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget19.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup79Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget19.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup75Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/Generated150Widget23.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedChickenThingSkinlessWidget23.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup80Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/Generated150Widget22.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup78Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup52Widget7.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget18.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget18.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle13Widget6.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup77Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/Generated450Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup21Widget3.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGroup53Widget24.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedCARTWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/Generated35Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget17.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcheckoutwidget/generated/GeneratedTotal485Widget.dart';

/* Frame checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 127.23260498046875,
                      child: GeneratedRectangle13Widget6(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget18(),
                    ),
                    Positioned(
                      left: 261.37060546875,
                      top: 161.2811737060547,
                      right: null,
                      bottom: null,
                      width: 82.707275390625,
                      height: 26.142982482910156,
                      child: GeneratedGroup76Widget2(),
                    ),
                    Positioned(
                      left: 261.37060546875,
                      top: 291.08721923828125,
                      right: null,
                      bottom: null,
                      width: 82.707275390625,
                      height: 26.142982482910156,
                      child: GeneratedGroup77Widget2(),
                    ),
                    Positioned(
                      left: 261.37060546875,
                      top: 419.8937072753906,
                      right: null,
                      bottom: null,
                      width: 82.707275390625,
                      height: 26.142982482910156,
                      child: GeneratedGroup79Widget(),
                    ),
                    Positioned(
                      left: 324.79638671875,
                      top: 173.6072998046875,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle28Widget1(),
                    ),
                    Positioned(
                      left: 324.79638671875,
                      top: 303.413330078125,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle31Widget(),
                    ),
                    Positioned(
                      left: 324.79638671875,
                      top: 432.2198181152344,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle34Widget(),
                    ),
                    Positioned(
                      left: 268.22900390625,
                      top: 173.6072998046875,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle29Widget2(),
                    ),
                    Positioned(
                      left: 268.22900390625,
                      top: 303.413330078125,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle32Widget(),
                    ),
                    Positioned(
                      left: 268.22900390625,
                      top: 432.2198181152344,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle35Widget(),
                    ),
                    Positioned(
                      left: 331.75341796875,
                      top: 168.14129638671875,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle30Widget(),
                    ),
                    Positioned(
                      left: 331.75341796875,
                      top: 297.94732666015625,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle33Widget(),
                    ),
                    Positioned(
                      left: 331.75341796875,
                      top: 426.7538146972656,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle36Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 986.758056640625,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 267.53216552734375,
                      child: GeneratedGroup75Widget3(),
                    ),
                    Positioned(
                      left: 162.5,
                      top: 45.5,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 27.0,
                      child: GeneratedCARTWidget(),
                    ),
                    Positioned(
                      left: 15.755859375,
                      top: 690.6027221679688,
                      right: null,
                      bottom: null,
                      width: 343.00006103515625,
                      height: 52.0,
                      child: GeneratedGroup52Widget7(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 104.03387451171875,
                      right: null,
                      bottom: null,
                      width: 193.2138671875,
                      height: 21.0,
                      child: GeneratedChickenThingSkinlessWidget21(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 233.83990478515625,
                      right: null,
                      bottom: null,
                      width: 193.2138671875,
                      height: 21.0,
                      child: GeneratedChickenThingSkinlessWidget22(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 362.6463928222656,
                      right: null,
                      bottom: null,
                      width: 193.2138671875,
                      height: 21.0,
                      child: GeneratedChickenThingSkinlessWidget23(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 165.3526611328125,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 23.0,
                      child: Generated150Widget21(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 295.15869140625,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 23.0,
                      child: Generated150Widget22(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 423.9651794433594,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 23.0,
                      child: Generated150Widget23(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 104.03387451171875,
                      right: null,
                      bottom: null,
                      width: 120.6573715209961,
                      height: 86.68103790283203,
                      child: GeneratedGroup53Widget24(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 233.83990478515625,
                      right: null,
                      bottom: null,
                      width: 120.6573715209961,
                      height: 86.68103790283203,
                      child: GeneratedGroup78Widget2(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 362.6463928222656,
                      right: null,
                      bottom: null,
                      width: 120.6573715209961,
                      height: 86.68103790283203,
                      child: GeneratedGroup80Widget(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 123.6246337890625,
                      right: null,
                      bottom: null,
                      width: 208.13623046875,
                      height: 36.0,
                      child: GeneratedGrossWt900gmsNetWt500gmsWidget17(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 253.4306640625,
                      right: null,
                      bottom: null,
                      width: 208.13623046875,
                      height: 36.0,
                      child: GeneratedGrossWt900gmsNetWt500gmsWidget18(),
                    ),
                    Positioned(
                      left: 152.5,
                      top: 382.2371520996094,
                      right: null,
                      bottom: null,
                      width: 208.13623046875,
                      height: 36.0,
                      child: GeneratedGrossWt900gmsNetWt500gmsWidget19(),
                    ),
                    Positioned(
                      left: -0.5,
                      top: 0.0,
                      right: 0.5,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget19(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 213.0884552001953,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 1.0,
                      child: GeneratedLine1Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 341.89495849609375,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 1.0,
                      child: GeneratedLine2Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 514.826416015625,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 1.0,
                      child: GeneratedLine3Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 471.701416015625,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 1.0,
                      child: GeneratedLine6Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 599.1856689453125,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 1.0,
                      child: GeneratedLine5Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 599.1856689453125,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 1.0,
                      child: GeneratedLine4Widget(),
                    ),
                    Positioned(
                      left: 192.93798828125,
                      top: 530.6384887695312,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 24.0,
                      child: GeneratedPrice3itemsWidget(),
                    ),
                    Positioned(
                      left: 194.93798828125,
                      top: 562.2294921875,
                      right: null,
                      bottom: null,
                      width: 105.0,
                      height: 24.0,
                      child: GeneratedDeliveryFeesWidget(),
                    ),
                    Positioned(
                      left: 320.0,
                      top: 532.6384887695312,
                      right: null,
                      bottom: null,
                      width: 44.0,
                      height: 27.0,
                      child: Generated450Widget(),
                    ),
                    Positioned(
                      left: 330.0,
                      top: 564.2294921875,
                      right: null,
                      bottom: null,
                      width: 34.0,
                      height: 27.0,
                      child: Generated35Widget(),
                    ),
                    Positioned(
                      left: 278.755859375,
                      top: 606.9136352539062,
                      right: null,
                      bottom: null,
                      width: 82.0,
                      height: 20.0,
                      child: GeneratedTotal485Widget(),
                    ),
                    Positioned(
                      left: 12.5,
                      top: 479.5185546875,
                      right: null,
                      bottom: null,
                      width: 142.0,
                      height: 25.0,
                      child: GeneratedHaveapromocodeWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 58.0,
              child: GeneratedGroup21Widget3(),
            )
          ]),
    ));
  }
}
