import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/Generated600px600pxWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/Generated700px360pxWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedProductImagesWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedImagesizeinpixelsWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedBannerAndroidWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedProductThumbnailSizeWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/Generated1InventoryShouldbeaddedasnoofitemsnotintotalweightWidge.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedImageexportguideWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedBannnerWebWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/Generated280px200pxWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/GeneratedOtherGuidesWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/Generated1440px550pxWidget.dart';
import 'package:flutterapp/klickfreshapp/generateda41widget/generated/Generated1UsethePNGorJPGFormatforimages2Exportimagesfromphotosho.dart';

/* Frame A4 - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedA41Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1415.1259765625,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1000.0,
                      height: 1415.1259765625,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 475.13531494140625,
                              right: null,
                              bottom: null,
                              width: 166.0,
                              height: 30.0,
                              child: GeneratedBannerAndroidWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 612.7236938476562,
                              right: null,
                              bottom: null,
                              width: 245.0,
                              height: 30.0,
                              child: GeneratedProductThumbnailSizeWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 541.9745483398438,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 30.0,
                              child: GeneratedBannnerWebWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 679.56298828125,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 30.0,
                              child: GeneratedProductImagesWidget(),
                            ),
                            Positioned(
                              left: 351.9915466308594,
                              top: 475.13531494140625,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 30.0,
                              child: Generated700px360pxWidget(),
                            ),
                            Positioned(
                              left: 351.9915466308594,
                              top: 612.7236938476562,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 30.0,
                              child: Generated280px200pxWidget(),
                            ),
                            Positioned(
                              left: 351.9915466308594,
                              top: 541.9745483398438,
                              right: null,
                              bottom: null,
                              width: 167.0,
                              height: 30.0,
                              child: Generated1440px550pxWidget(),
                            ),
                            Positioned(
                              left: 351.9915466308594,
                              top: 679.56298828125,
                              right: null,
                              bottom: null,
                              width: 166.0,
                              height: 30.0,
                              child: Generated600px600pxWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 98.79159545898438,
                              right: null,
                              bottom: null,
                              width: 324.0,
                              height: 50.0,
                              child: GeneratedImageexportguideWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 383.3595886230469,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 50.0,
                              child: GeneratedImagesizeinpixelsWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 790.3185424804688,
                              right: null,
                              bottom: null,
                              width: 225.0,
                              height: 50.0,
                              child: GeneratedOtherGuidesWidget(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 165.6305694580078,
                              right: null,
                              bottom: null,
                              width: 775.0,
                              height: 158.0,
                              child:
                                  Generated1UsethePNGorJPGFormatforimages2Exportimagesfromphotosho(),
                            ),
                            Positioned(
                              left: 56.36515808105469,
                              top: 861.0679931640625,
                              right: null,
                              bottom: null,
                              width: 628.0,
                              height: 54.0,
                              child:
                                  Generated1InventoryShouldbeaddedasnoofitemsnotintotalweightWidge(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
