import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedDeliveryinstructionsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedGroup75Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget16.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedRectangle27Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedImage4Widget23.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedIforderedbefore300PMthensamedaydeliveryotherwisewillbed.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedChickenThingSkinlessWidget18.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedRectangle13Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedImage5Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedBack_blackWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget16.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedGroup52Widget6.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedCHICKENWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/Generated150Widget19.dart';
import 'package:flutterapp/klickfreshapp/generatedproductdetailswidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget17.dart';

/* Frame product details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductdetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 391.283935546875,
                top: 0.000030517578125,
                right: null,
                bottom: null,
                width: 395.13287353515625,
                height: 287.523193359375,
                child: GeneratedImage4Widget23(),
              ),
              Positioned(
                left: 391.283935546875,
                top: -36.5816650390625,
                right: null,
                bottom: null,
                width: 395.13287353515625,
                height: 173.33045959472656,
                child: GeneratedImage5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget16(),
              ),
              Positioned(
                left: 16.0,
                top: 302.2815856933594,
                right: null,
                bottom: null,
                width: 340.5,
                height: 24.0,
                child: GeneratedChickenThingSkinlessWidget18(),
              ),
              Positioned(
                left: 16.0,
                top: 398.03448486328125,
                right: null,
                bottom: null,
                width: 343.5,
                height: 27.0,
                child: GeneratedDetailsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 536.8497314453125,
                right: null,
                bottom: null,
                width: 340.5,
                height: 24.0,
                child: GeneratedDeliveryinstructionsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 328.8724060058594,
                right: null,
                bottom: null,
                width: 340.5,
                height: 22.0,
                child: GeneratedGrossWt900gmsNetWt500gmsWidget16(),
              ),
              Positioned(
                left: 16.0,
                top: 986.758056640625,
                right: null,
                bottom: null,
                width: 343.0,
                height: 267.53216552734375,
                child: GeneratedGroup75Widget2(),
              ),
              Positioned(
                left: 19.5,
                top: 46.5,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget6(),
              ),
              Positioned(
                left: 145.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 88.0,
                height: 27.0,
                child: GeneratedCHICKENWidget2(),
              ),
              Positioned(
                left: -3.84912109375,
                top: 738.6762084960938,
                right: null,
                bottom: null,
                width: 382.6983947753906,
                height: 74.32378387451172,
                child: GeneratedRectangle27Widget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 10.39727783203125,
                width: 252.75619506835938,
                height: 52.0,
                child: TransformHelper.translate(
                    x: 44.88, y: 0.00, z: 0, child: GeneratedGroup52Widget6()),
              ),
              Positioned(
                left: 16.0,
                top: 423.3497314453125,
                right: null,
                bottom: null,
                width: 346.3280029296875,
                height: 90.0,
                child:
                    GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame(),
              ),
              Positioned(
                left: 16.0,
                top: 562.1649169921875,
                right: null,
                bottom: null,
                width: 346.3280029296875,
                height: 68.0,
                child:
                    GeneratedIforderedbefore300PMthensamedaydeliveryotherwisewillbed(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget17(),
              ),
              Positioned(
                left: 29.5,
                top: 768.6027221679688,
                right: null,
                bottom: null,
                width: 40.85194778442383,
                height: 24.0,
                child: Generated150Widget19(),
              )
            ]),
      ),
    ));
  }
}
