import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedEditProfileWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedVectorWidget616.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedGroup97Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedGroup98Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedLineWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedVishalSoniWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedVectorWidget620.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedVishaalsoni15gmailcomWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedGroup96Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedStatusbarsiPhone8statusbarlightWidget38.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedPROFILEWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedFAQsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedLogoWidget4.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedTermsandconditionsWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedStatusbarsiPhone8statusbarlightWidget39.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedSupportWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedGroup21Widget8.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedWhileusingMachrangaWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedContactdetailsMachrangaWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedGroup75Widget8.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedLineWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedVectorWidget618.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedRectangle13Widget16.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedRectangleWidget152.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedLOGOUTWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedprofilewidget8/generated/GeneratedFrequentlyaskedquestionsWidget.dart';

/* Frame profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 127.23260498046875,
                      child: GeneratedRectangle13Widget16(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget38(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 986.758056640625,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 267.53216552734375,
                      child: GeneratedGroup75Widget8(),
                    ),
                    Positioned(
                      left: 148.5,
                      top: 45.5,
                      right: null,
                      bottom: null,
                      width: 81.0,
                      height: 27.0,
                      child: GeneratedPROFILEWidget(),
                    ),
                    Positioned(
                      left: -0.5,
                      top: 0.0,
                      right: 0.5,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget39(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 466.8162536621094,
                      right: null,
                      bottom: null,
                      width: 285.0,
                      height: 1.0,
                      child: GeneratedLineWidget(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 405.8164367675781,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 24.0,
                      child: GeneratedSupportWidget(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 427.8164367675781,
                      right: null,
                      bottom: null,
                      width: 177.0,
                      height: 22.0,
                      child: GeneratedContactdetailsMachrangaWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 402.8164367675781,
                      right: null,
                      bottom: null,
                      width: 44.0,
                      height: 44.0,
                      child: GeneratedGroup97Widget(),
                    ),
                    Positioned(
                      left: 347.474365234375,
                      top: 415.8164367675781,
                      right: null,
                      bottom: null,
                      width: 10.477941513061523,
                      height: 17.0,
                      child: GeneratedVectorWidget616(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 385.8163757324219,
                      right: null,
                      bottom: null,
                      width: 285.0,
                      height: 1.0,
                      child: GeneratedLineWidget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 320.8163146972656,
                      right: null,
                      bottom: null,
                      width: 44.0,
                      height: 44.0,
                      child: GeneratedGroup96Widget(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 323.8163146972656,
                      right: null,
                      bottom: null,
                      width: 50.0,
                      height: 24.0,
                      child: GeneratedFAQsWidget(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 345.8163146972656,
                      right: null,
                      bottom: null,
                      width: 179.0,
                      height: 22.0,
                      child: GeneratedFrequentlyaskedquestionsWidget(),
                    ),
                    Positioned(
                      left: 347.474365234375,
                      top: 333.8163146972656,
                      right: null,
                      bottom: null,
                      width: 10.477941513061523,
                      height: 17.0,
                      child: GeneratedVectorWidget618(),
                    ),
                    Positioned(
                      left: 74.00003051757812,
                      top: 489.8162536621094,
                      right: null,
                      bottom: null,
                      width: 171.0,
                      height: 21.0,
                      child: GeneratedTermsandconditionsWidget(),
                    ),
                    Positioned(
                      left: 74.00003051757812,
                      top: 511.8162536621094,
                      right: null,
                      bottom: null,
                      width: 157.0,
                      height: 22.0,
                      child: GeneratedWhileusingMachrangaWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 486.8162536621094,
                      right: null,
                      bottom: null,
                      width: 44.0,
                      height: 44.0,
                      child: GeneratedGroup98Widget(),
                    ),
                    Positioned(
                      left: 347.4742736816406,
                      top: 499.8162536621094,
                      right: null,
                      bottom: null,
                      width: 10.477941513061523,
                      height: 17.0,
                      child: GeneratedVectorWidget620(),
                    ),
                    Positioned(
                      left: 136.787109375,
                      top: 107.38336181640625,
                      right: null,
                      bottom: null,
                      width: 101.212890625,
                      height: 101.212890625,
                      child: GeneratedRectangleWidget152(),
                    ),
                    Positioned(
                      left: 120.8935546875,
                      top: 214.0908203125,
                      right: null,
                      bottom: null,
                      width: 133.0,
                      height: 31.0,
                      child: GeneratedVishalSoniWidget(),
                    ),
                    Positioned(
                      left: 102.8935546875,
                      top: 243.09085083007812,
                      right: null,
                      bottom: null,
                      width: 174.0,
                      height: 22.0,
                      child: GeneratedVishaalsoni15gmailcomWidget(),
                    ),
                    Positioned(
                      left: 151.8935546875,
                      top: 264.8163146972656,
                      right: null,
                      bottom: null,
                      width: 72.0,
                      height: 19.0,
                      child: GeneratedEditProfileWidget(),
                    ),
                    Positioned(
                      left: 159.5,
                      top: 718.963134765625,
                      right: null,
                      bottom: null,
                      width: 61.0,
                      height: 24.0,
                      child: GeneratedLOGOUTWidget(),
                    ),
                    Positioned(
                      left: 137.35975646972656,
                      top: 607.5424194335938,
                      right: null,
                      bottom: null,
                      width: 100.28047943115234,
                      height: 94.5018539428711,
                      child: GeneratedLogoWidget4(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 58.0,
              child: GeneratedGroup21Widget8(),
            )
          ]),
    ));
  }
}
