import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangleWidget155.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangleWidget158.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedVishalSoniWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedNewPasswordWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangleWidget157.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedVishaalsoni15gmailcomWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedName_inputWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget40.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangle13Widget17.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedChangepasswordWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangleWidget156.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedPhone_inputWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedCurrentPasswordWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedBxbxlockWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangle27Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedMail_inputWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedEDITPROFILEWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/Generated7742150168Widget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangleWidget153.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedRectangleWidget154.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedGroup52Widget11.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedBxbxlockWidget.dart';
import 'package:flutterapp/klickfreshapp/generatededit_profilewidget/generated/GeneratedBack_blackWidget14.dart';

/* Frame edit_profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEdit_profileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 86.78026580810547,
                right: null,
                bottom: null,
                width: 374.93988037109375,
                height: 741.4043579101562,
                child: GeneratedRectangle13Widget17(),
              ),
              Positioned(
                left: 136.787109375,
                top: 107.38336181640625,
                right: null,
                bottom: null,
                width: 101.212890625,
                height: 101.212890625,
                child: GeneratedRectangleWidget153(),
              ),
              Positioned(
                left: 19.5,
                top: 47.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget14(),
              ),
              Positioned(
                left: 126.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 123.0,
                height: 24.0,
                child: GeneratedEDITPROFILEWidget(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget40(),
              ),
              Positioned(
                left: 16.0,
                top: 531.6377563476562,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRectangleWidget154(),
              ),
              Positioned(
                left: 68.5,
                top: 543.6377563476562,
                right: null,
                bottom: null,
                width: 135.0,
                height: 24.0,
                child: GeneratedCurrentPasswordWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 590.6377563476562,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRectangleWidget155(),
              ),
              Positioned(
                left: 68.5,
                top: 602.6377563476562,
                right: null,
                bottom: null,
                width: 115.0,
                height: 24.0,
                child: GeneratedNewPasswordWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 602.6377563476562,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxlockWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 543.6377563476562,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxlockWidget1(),
              ),
              Positioned(
                left: 19.5,
                top: 496.63775634765625,
                right: null,
                bottom: null,
                width: 143.0,
                height: 21.0,
                child: GeneratedChangepasswordWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 408.7547607421875,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRectangleWidget156(),
              ),
              Positioned(
                left: 16.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRectangleWidget157(),
              ),
              Positioned(
                left: 68.5,
                top: 420.7547607421875,
                right: null,
                bottom: null,
                width: 101.0,
                height: 27.0,
                child: Generated7742150168Widget(),
              ),
              Positioned(
                left: 68.5,
                top: 304.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 24.0,
                child: GeneratedVishalSoniWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRectangleWidget158(),
              ),
              Positioned(
                left: 68.5,
                top: 363.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 27.0,
                child: GeneratedVishaalsoni15gmailcomWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 361.5,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMail_inputWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 419.7547607421875,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPhone_inputWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedName_inputWidget(),
              ),
              Positioned(
                left: -3.84912109375,
                top: 738.6762084960938,
                right: null,
                bottom: null,
                width: 382.6983947753906,
                height: 74.32378387451172,
                child: GeneratedRectangle27Widget4(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 10.39727783203125,
                width: 343.00006103515625,
                height: 52.0,
                child: TransformHelper.translate(
                    x: -0.24, y: 0.00, z: 0, child: GeneratedGroup52Widget11()),
              )
            ]),
      ),
    ));
  }
}
