import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedChickenThingSkinlessWidget33.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedQty1Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget20.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedORderstatusWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedGrossWt900gmsNetWt500gmsWidget21.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedConfirmedWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedReceivedWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedEllipse20Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedGroup53Widget30.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedGroup78Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedSucccessWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedFrame10Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedOutfordeliveryWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedOrderedSuccessfullWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedDeliveredWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedGroup76Widget5.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget35.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedQty1Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedRectangle13Widget14.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedChickenThingSkinlessWidget34.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedEllipse21Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedDeliveringhereWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedStatusbarsiPhone8statusbarlightWidget34.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedORDERDETAILSWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/Generated150Widget30.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/GeneratedRectangle41Widget2.dart';
import 'package:flutterapp/klickfreshapp/generatedorder_successfulwidget/generated/Generated150Widget31.dart';

/* Frame order_successful
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrder_successfulWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 841.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 127.23260498046875,
                child: GeneratedRectangle13Widget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget34(),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget35(),
              ),
              Positioned(
                left: 99.0,
                top: 140.22500610351562,
                right: null,
                bottom: null,
                width: 179.0,
                height: 24.0,
                child: GeneratedOrderedSuccessfullWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 391.10699462890625,
                right: null,
                bottom: null,
                width: 144.0,
                height: 24.0,
                child: GeneratedORDERDETAILSWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 696.2677612304688,
                right: null,
                bottom: null,
                width: 164.0,
                height: 24.0,
                child: GeneratedDeliveringhereWidget(),
              ),
              Positioned(
                left: 149.5087890625,
                top: 56.5,
                right: null,
                bottom: null,
                width: 75.48269653320312,
                height: 75.48269653320312,
                child: GeneratedSucccessWidget(),
              ),
              Positioned(
                left: 152.5,
                top: 428.42706298828125,
                right: null,
                bottom: null,
                width: 193.2138671875,
                height: 20.0,
                child: GeneratedChickenThingSkinlessWidget33(),
              ),
              Positioned(
                left: 152.5,
                top: 558.2330932617188,
                right: null,
                bottom: null,
                width: 193.2138671875,
                height: 20.0,
                child: GeneratedChickenThingSkinlessWidget34(),
              ),
              Positioned(
                left: 325.63623046875,
                top: 488.74578857421875,
                right: null,
                bottom: null,
                width: 38.0,
                height: 23.0,
                child: Generated150Widget30(),
              ),
              Positioned(
                left: 325.63623046875,
                top: 618.5518188476562,
                right: null,
                bottom: null,
                width: 38.0,
                height: 23.0,
                child: Generated150Widget31(),
              ),
              Positioned(
                left: 16.0,
                top: 428.42706298828125,
                right: null,
                bottom: null,
                width: 120.6573715209961,
                height: 86.68103790283203,
                child: GeneratedGroup53Widget30(),
              ),
              Positioned(
                left: 16.0,
                top: 558.2330932617188,
                right: null,
                bottom: null,
                width: 120.6573715209961,
                height: 86.68103790283203,
                child: GeneratedGroup78Widget4(),
              ),
              Positioned(
                left: 152.5,
                top: 448.01776123046875,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 36.0,
                child: GeneratedGrossWt900gmsNetWt500gmsWidget20(),
              ),
              Positioned(
                left: 152.5,
                top: 489.74578857421875,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 19.0,
                child: GeneratedQty1Widget(),
              ),
              Positioned(
                left: 152.5,
                top: 619.5518188476562,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 19.0,
                child: GeneratedQty1Widget1(),
              ),
              Positioned(
                left: 152.5,
                top: 577.8237915039062,
                right: null,
                bottom: null,
                width: 208.13623046875,
                height: 36.0,
                child: GeneratedGrossWt900gmsNetWt500gmsWidget21(),
              ),
              Positioned(
                left: 16.0,
                top: 537.4816284179688,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 15.63623046875,
                top: 729.2378540039062,
                right: null,
                bottom: null,
                width: 343.0,
                height: 80.41822052001953,
                child: GeneratedRectangle41Widget2(),
              ),
              Positioned(
                left: 29.5283203125,
                top: 747.1088256835938,
                right: null,
                bottom: null,
                width: 316.60791015625,
                height: 46.0,
                child:
                    Generated1667thBmainroad4thphaseJPNagarBangalore560076Widget4(),
              ),
              Positioned(
                left: 119.49551391601562,
                top: 171.25950622558594,
                right: null,
                bottom: null,
                width: 136.00936889648438,
                height: 33.50453567504883,
                child: GeneratedGroup76Widget5(),
              ),
              Positioned(
                left: 16.900390625,
                top: 252.69992065429688,
                right: null,
                bottom: null,
                width: 138.0,
                height: 24.0,
                child: GeneratedORderstatusWidget(),
              ),
              Positioned(
                left: 16.900390625,
                top: 334.2120666503906,
                right: null,
                bottom: null,
                width: 56.0,
                height: 20.0,
                child: GeneratedReceivedWidget(),
              ),
              Positioned(
                left: 105.296875,
                top: 334.2120666503906,
                right: null,
                bottom: null,
                width: 63.0,
                height: 20.0,
                child: GeneratedConfirmedWidget(),
              ),
              Positioned(
                left: 194.900390625,
                top: 334.2120666503906,
                right: null,
                bottom: null,
                width: 88.0,
                height: 17.0,
                child: GeneratedOutfordeliveryWidget(),
              ),
              Positioned(
                left: 304.1162109375,
                top: 334.2120666503906,
                right: null,
                bottom: null,
                width: 57.0,
                height: 20.0,
                child: GeneratedDeliveredWidget(),
              ),
              Positioned(
                left: 31.498046875,
                top: 315.3819885253906,
                right: null,
                bottom: null,
                width: 3.6725003719329834,
                height: 309.0936584472656,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 31.498046875,
                top: 315.3819885253906,
                right: null,
                bottom: null,
                width: 3.6725003719329834,
                height: 108.05970764160156,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 18.900390625,
                top: 328.9459533691406,
                right: null,
                bottom: null,
                width: 30.799999237060547,
                height: 339.20001220703125,
                child: GeneratedFrame10Widget2(),
              ),
              Positioned(
                left: 26.52392578125,
                top: 321.0245666503906,
                right: null,
                bottom: null,
                width: 14.957195281982422,
                height: 14.957195281982422,
                child: GeneratedEllipse20Widget1(),
              ),
              Positioned(
                left: 129.62158203125,
                top: 321.0245666503906,
                right: null,
                bottom: null,
                width: 14.957195281982422,
                height: 14.957195281982422,
                child: GeneratedEllipse21Widget1(),
              )
            ]),
      ),
    ));
  }
}
