import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedsplashwidget1/generated/GeneratedMaskGroupWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatedsplashwidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedsplashwidget1/generated/GeneratedLogoWidget3.dart';
import 'package:flutterapp/klickfreshapp/generatedsplashwidget1/generated/GeneratedMaskGroupWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedsplashwidget1/generated/GeneratedMaskGroupWidget.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedWelcomeWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -368.2373046875,
                  top: -267.5962219238281,
                  right: null,
                  bottom: null,
                  width: 634.5501708984375,
                  height: 634.5501708984375,
                  child: GeneratedMaskGroupWidget(),
                ),
                Positioned(
                  left: 722.1751098632812,
                  top: 1098.039306640625,
                  right: null,
                  bottom: null,
                  width: 634.5501708984375,
                  height: 634.5501708984375,
                  child: GeneratedMaskGroupWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 495.0,
                  right: null,
                  bottom: null,
                  width: 377.0,
                  height: 317.0,
                  child: GeneratedMaskGroupWidget2(),
                ),
                Positioned(
                  left: -0.5,
                  top: 0.0,
                  right: 0.5,
                  bottom: null,
                  width: null,
                  height: 20.0,
                  child: GeneratedStatusbarsiPhone8statusbarlightWidget(),
                ),
                Positioned(
                  left: 97.90283203125,
                  top: 167.85389709472656,
                  right: null,
                  bottom: null,
                  width: 179.19432067871094,
                  height: 168.86831665039062,
                  child: GeneratedLogoWidget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
