import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedmaskgroupwidget78/generated/GeneratedRectangleWidget198.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaskGroupWidget78 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 749.6220703125,
      height: 820.1282958984375,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 749.6220703125,
              height: 820.1282958984375,
              child: GeneratedRectangleWidget198(),
            )
          ]),
    ));
  }
}
