import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget2.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedDonthaveanaccountSignupWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedBack_blackWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedAntdesigneyeinvisiblefilledWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedGroup52Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedwelcomewidget1/generated/GeneratedMobileNoWidget.dart';

/* Frame welcome
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -0.5,
                top: 0.0,
                right: 0.5,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedStatusbarsiPhone8statusbarlightWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 28.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 25.0,
                child: GeneratedMobileNoWidget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 644.017333984375,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 564.0,
                width: 343.0,
                height: 1.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 109.6632080078125,
                top: 391.5681457519531,
                right: null,
                bottom: null,
                width: 166.0,
                height: 50.0,
                child: GeneratedDonthaveanaccountSignupWidget(),
              ),
              Positioned(
                left: 234.00006103515625,
                top: 267.775390625,
                right: null,
                bottom: null,
                width: 127.0,
                height: 26.0,
                child: GeneratedForgotPasswordWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 324.9656677246094,
                right: null,
                bottom: null,
                width: 343.00006103515625,
                height: 52.0,
                child: GeneratedGroup52Widget1(),
              ),
              Positioned(
                left: 19.5,
                top: 47.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedBack_blackWidget(),
              ),
              Positioned(
                left: 157.5,
                top: 45.5,
                right: null,
                bottom: null,
                width: 63.0,
                height: 27.0,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 22.0,
                child: GeneratedAntdesigneyeinvisiblefilledWidget(),
              )
            ]),
      ),
    ));
  }
}
