import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedmaskgroupwidget74/generated/GeneratedMaskGroupWidget75.dart';
import 'package:flutterapp/klickfreshapp/generatedmaskgroupwidget74/generated/GeneratedImage18Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedmaskgroupwidget74/generated/GeneratedImage19Widget.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaskGroupWidget74 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 470.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1440.0,
              height: 470.0,
              child: GeneratedMaskGroupWidget75(),
            ),
            Positioned(
              left: -159.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1659.0,
              height: 470.0,
              child: GeneratedImage18Widget(),
            ),
            Positioned(
              left: -62.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1504.0,
              height: 470.0,
              child: GeneratedImage19Widget(),
            )
          ]),
    ));
  }
}
