import 'package:flutter/material.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedGroup75Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedFrame7Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedGroup71Widget14.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedGroup77Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedRectangle13Widget4.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedGroup93Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedGroup76Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedCHICKENWidget1.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedBack_blackWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget14.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedStatusbarsiPhone8statusbarlightWidget15.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/klickfreshapp/generatedcatergorywidget1/generated/GeneratedGroup78Widget1.dart';

/* Frame catergory
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCatergoryWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 247, 247, 247),
                      ),
                    ),
                    Positioned(
                      left: -6.950927734375,
                      top: -17.523193359375,
                      right: null,
                      bottom: null,
                      width: 389.1697692871094,
                      height: 193.66864013671875,
                      child: GeneratedRectangle29Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 127.23260498046875,
                      child: GeneratedRectangle13Widget4(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget14(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 188.69638061523438,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 267.3105773925781,
                      child: GeneratedGroup76Widget1(),
                    ),
                    Positioned(
                      left: 260.7216796875,
                      top: 414.76068115234375,
                      right: null,
                      bottom: null,
                      width: 82.707275390625,
                      height: 26.142982482910156,
                      child: GeneratedGroup71Widget14(),
                    ),
                    Positioned(
                      left: 324.147705078125,
                      top: 427.1867370605469,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle22Widget(),
                    ),
                    Positioned(
                      left: 267.580322265625,
                      top: 427.1867370605469,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle24Widget(),
                    ),
                    Positioned(
                      left: 331.1044921875,
                      top: 421.7207336425781,
                      right: null,
                      bottom: null,
                      width: 12.422745704650879,
                      height: 1.4907172918319702,
                      child: GeneratedRectangle23Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 475.9201354980469,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 267.3105773925781,
                      child: GeneratedGroup77Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 763.1436767578125,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 267.3105773925781,
                      child: GeneratedGroup78Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 986.758056640625,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 267.53216552734375,
                      child: GeneratedGroup75Widget1(),
                    ),
                    Positioned(
                      left: 19.5,
                      top: 46.5,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 20.0,
                      child: GeneratedBack_blackWidget4(),
                    ),
                    Positioned(
                      left: 145.5,
                      top: 45.5,
                      right: null,
                      bottom: null,
                      width: 88.0,
                      height: 27.0,
                      child: GeneratedCHICKENWidget1(),
                    ),
                    Positioned(
                      left: -0.5,
                      top: 0.0,
                      right: 0.5,
                      bottom: null,
                      width: null,
                      height: 20.0,
                      child: GeneratedStatusbarsiPhone8statusbarlightWidget15(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 86.098388671875,
                      right: null,
                      bottom: null,
                      width: 342.0,
                      height: 84.0,
                      child: GeneratedFrame7Widget4(),
                    )
                  ]),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: -3.3237838745117188,
              width: 382.6983947753906,
              height: 74.32378387451172,
              child: TransformHelper.translate(
                  x: 0.00, y: 0.00, z: 0, child: GeneratedGroup93Widget()),
            )
          ]),
    ));
  }
}
