import 'package:flutter/material.dart';

/* Text https://compressor.io/
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHttpscompressorioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''https://compressor.io/''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.1718749655675056,
        fontSize: 51.931739807128906,
        fontFamily: 'Biotif',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
